project:
  type: website

author:
  - name: Ling Lu
    affiliations:
      - id: U15738240
        name: Boston University
        city: Boston
        state: MA
  - name: Luoyan Zhang
    affiliations:
      - id: U00607539
        name: Boston University
        city: Boston
        state: MA
  - name: Yinuo Wang
    affiliations:
      - id: U78839500
        name: Boston University
        city: Boston
        state: MA

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_analysis.ipynb
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.ipynb
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd/ipynb
        text: "ML Methods"
      - href: nlp_methods.qmd/ipynb
        text: "NLP Methods"
format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true
bibliography: references.bib
csl: csl/econometrica.csl